@startuml
'https://plantuml.com/sequence-diagram


Entity <|--Hero
Entity <|--Monster
Entity <|--Npc
Monster <|--Fantome
GamePanel "1" -- "1" Player
Entity <|-- Player

class labyrinthe{
}
abstract class Entity {
int x,y
int speed
int Hp
BufferedImage up1,up2, down1,down2,
left1,left2,right1,right2
String direction
int spriteCounter
int spriteNum
GamePanel gp
setAction():void

}

class GamePanel {
        - monstre: Monstre
        - originalTileSize: int
        - scale: int
        - tileSize: int
        - maxScreenCol: int
        - maxScreenRow: int
        - screenWidth: int
        - screenHeight: int
        - labyrinth: Labyrinth
        - p1: Personnage 
        - thread: Thread
        - control: Controller
        - player: Player
        - checker: Collision

        + GamePanel()
        + setMonstre(monstre: Monstre): void
        + getTileSize(): int
        + startThread(): void
        + run(): void
        + update(): void
        + paintComponent(g: Graphics): void
}

class Hero {
Controller keyH
setAction():void
}

class Monster {
String power
setAction():void
}

class Fantome {
setAction():void
}
class Npc{
setAction():void
}


class Controller {
    - up: boolean
    - left: boolean
    - down: boolean
    - right: boolean
    - attaque: boolean

    + keyTyped(e: KeyEvent): void
    + keyPressed(e: KeyEvent): void
    + keyReleased(e: KeyEvent): void
}



@enduml