@startuml
actor       Game_Player       as Gamer
participant Gamepanel as Gamepanel


Gamer -> Gamepanel: Choisir le Niveau de difficulté (niveau)
Gamepanel --> Gamer : Niveau Sélectionné()
Gamer -> Gamepanel: Executer le Jeu
Gamepanel -> Labyrinthe : Générer la labyrinthe
Labyrinthe <- Labyrinthe : Labyrinthe générée
loop posplayer == Obstacle 
    Labyrinthe -> Player : Génerer la position initiale du Player
end

Player --> Labyrinthe : Position du joueur initialisé

Labyrinthe --> Gamepanel : Jeu Initialisé

participant Controller as Controller

loop point de vie >100 || Gagné == 0 
    Gamer-> Controller : Appuyer sur une touche (char)
    Controller -> Labyrinthe : Verifier le type de case
    Labyrinthe --> Controller : envoyer le type de la case()
    alt  Mouvement addmisible
    Controller -> Player : Mise a jour des coordonées du Joueur
    else 

    end
end

@enduml
